[preferred]
# Use Hyprland for what it's good at (Screen sharing, global shortcuts etc.)
default=hyprland;gtk
# Use GTK for everything else (File Choosers, App Pickers)
org.freedesktop.impl.portal.FileChooser=gtk
org.freedesktop.impl.portal.AppChooser=gtk
