# Fuzzel configuration file (Tokyonight Night Theme)
[main]
font = CaskaydiaCove Nerd Font:weight=Regular:size=9.5
terminal = kitty                 # Your preferred terminal emulator
sort-result = true
prompt = "  "
hide-prompt = no
placeholder ="Search..."
line-height = 20
icons-enabled = yes
icon-theme = Papirus-Dark
#icon-theme = Neuwaita
scaling-filter = box
lines = 10                       # Number of results to show
width = 62                       # Width in character cell
horizontal-pad = 12              # Horizontal padding
vertical-pad = 5                 # Vertical padding
inner-pad = 5                    # Padding between prompt/results and border
y-margin = 10
x-margin = 0
tabs = 4                         # Spaces per tab
show-actions = no                # Set to "yes" to show extra actions
layer = overlay
exit-on-keyboard-focus-loss = yes
dpi-aware = yes
use-bold = no
match-counter = true
match-mode = fzf
anchor = center
image-size-ratio = 0.5
enable-mouse = true

[colors]
# background=212337ff
# counter=c0caf5af
# placeholder = 93a1a170
# prompt = 93a1a18f
# text = c0caf5ff
# input = c0caf5ff
# match= f7768eff
# selection-match=82aaffff
# selection=4d4e73af
# selection-text=FFFFFFFF
# border=82aaffff

background=212337ff
counter=c0caf5bf
input = c0caf5f2
placeholder = 93a1a18f
prompt = c0caf5bf
text = c0caf5e8
match = f7768eff
selection-match = 0578ffff 
selection = 82aaffff
#selection=1d9bf0ff
selection-text = 1d2238ff
# border = 97e7fdff
border = 82aaffff

[border]
width = 2
radius = 0
