[main]
font=CaskaydiaCove Nerd Font:size=10.5
dpi-aware=no
shell=/usr/bin/zsh
letter-spacing=0
underline-thickness=1px
strikeout-thickness=1px
gamma-correct-blending=no
resize-keep-grid=no
initial-color-theme=dark
bold-text-in-bright=no
resize-delay-ms=20
selection-target=both
# RIGHTxTOPxLEFTxBOTTOM
pad=10x10x7x8

[bell]
system=no

[scrollback]
lines=2000
indicator-position=fixed
indicator-format=percentage

[cursor]
style=block
unfocused-style=hollow
blink=no

[mouse]
hide-when-typing=yes

[colors-dark]
cursor=212338 ff996c
background=212337
foreground=c0caf5
selection-foreground=c0caf5
selection-background=2d3f76
scrollback-indicator=1d2238 82aaff
# The eight basic ANSI colors (Black,Red,Green,Yellow,Blue,Magenta,Cyan,White)
regular0=1b1d2b
regular1=f7768e
regular2=9ece6a
regular3=e0af68
regular4=82aaff
regular5=bb9af7
regular6=7dcfff
regular7=a9b1d6
bright0=414868
bright1=f7768e
bright2=9ece6a
bright3=e0af68
bright4=82aaff
bright5=bb9af7
bright6=7dcfff
bright7=e3e7f6

[key-bindings]
scrollback-up-page=Control+Shift+Page_Up
scrollback-up-line=Control+Shift+Up
scrollback-down-page=Control+Shift+Page_Down
scrollback-down-line=Control+Shift+Down
scrollback-home=Control+Shift+Home
scrollback-end=Control+Shift+End
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
search-start=Control+Shift+f
font-increase=Control+plus Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+Shift+0 Control+Shift+KP_0
spawn-terminal=none
unicode-input=Control+Shift+u
show-urls-copy=Control+Shift+p
show-urls-launch=Control+Shift+o
prompt-prev=none
prompt-next=none

[search-bindings]
cancel=Control+c Escape
commit=Return
find-prev=none
find-next=none
cursor-left=none
cursor-left-word=none
cursor-right=none
cursor-right-word=none
cursor-home=none
cursor-end=none
delete-prev=none
delete-prev-word=none
delete-next=none
delete-next-word=none
delete-to-start=none
delete-to-end=none
extend-char=none
extend-to-word-boundary=none
extend-to-next-whitespace=none
extend-line-down=none
extend-backward-char=none
extend-backward-to-word-boundary=none
extend-backward-to-next-whitespace=none
extend-line-up=none
clipboard-paste=none
primary-paste=none
unicode-input=none
scrollback-up-page=none
scrollback-up-half-page=none
scrollback-up-line=none
scrollback-down-page=none
scrollback-down-half-page=none
scrollback-down-line=none
scrollback-home=none
scrollback-end=none

[url-bindings]
cancel=Control+c Escape
toggle-url-visible=t

[mouse-bindings]
primary-paste=none
select-begin=BTN_LEFT
select-begin-block=Control+BTN_LEFT
select-extend=none
select-extend-character-wise=none
select-word=none
select-word-whitespace=none
select-quote=none
select-row=none
