# ┏━┃┃ ┃━┏┛┏━┃┏━┛━┏┛┏━┃┏━┃━┏┛
# ┏━┃┃ ┃ ┃ ┃ ┃━━┃ ┃ ┏━┃┏┏┛ ┃ 
# ┛ ┛━━┛ ┛ ━━┛━━┛ ┛ ┛ ┛┛ ┛ ┛ 

# xdg env variables are important for xdp communication with wayland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = $HOME/.local/bin/scripts/xdp_nuclear_option.sh

# Cursor uniform across the system
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'; gsettings set org.gnome.desktop.interface cursor-size 24

# THEME uniform across system
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Tokyonight-B-LB-Dark-Moon"

# Waybar
exec-once = waybar 

# Notification Daemon
exec-once = mako 

# Udiskie for notifications related to mounted devices
exec-once = udiskie 

# Authentication daemon for hyprland
exec-once = systemctl --user start hyprpolkitagent 

# Wallpaper daemon
exec-once = awww-daemon

# hypridle listner daemon
exec-once = hypridle 

#clipboard manager
exec-once = wl-clip-persist -c regular # For persistent copy of clipboard content into cliphist
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store 

#X11
exec-once = xrdb -merge ~/.Xresources

#Plugins reload
exec-once = hyprpm reload

# The bracket part is the rule applied to the command following it --> for faster opening experience at the expense of slightly more ram usage
# exec-once = hyprctl -q dispatch exec '[workspace special:helium silent] helium-browser --new-session chrome://newtab'
# exec-once = hyprctl -q dispatch exec '[workspace 2 silent] app.zen_browser.zen  --new-session about:blank'
#Greetings
exec-once = notify-send "Hyprland" "Welcome Satya" -u normal -i ~/Pictures/icons/hyprland.png
