# ┛┏━ ┏━┃┃ ┃━┏┛
# ┃┃ ┃┏━┛┃ ┃ ┃ 
# ┛┛ ┛┛  ━━┛ ┛ 

input {
    kb_layout = us
    follow_mouse = 1
    repeat_delay = 350
    repeat_rate = 48
		sensitivity = 0
    touchpad {
        natural_scroll = true
    		scroll_factor = 0.35
    }
}

#MOUSE RAZER
device {
		name = razer-razer-deathadder-v2-x-hyperspeed-1
		enabled = true
    sensitivity = -0.88
    scroll_factor = 1
}
device {
		name = razer-razer-deathadder-v2-x-hyperspeed
		enabled = true
    sensitivity = -0.88
    scroll_factor = 1
}

#################
#### GESTURE ####
#################

# gesture = 3, horizontal, workspace
