# ┃┃┃┛┏━ ┏━ ┏━┃┃┃┃┏━┛
# ┃┃┃┃┃ ┃┃ ┃┃ ┃┃┃┃━━┃
# ━━┛┛┛ ┛━━ ━━┛━━┛━━┛

# !!!Rules are read from top to bottom so order is important, make sure specific rules of are written before general rule of same kind

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .* , suppress_event maximize
# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1,match:float 1,match:fullscreen 0,match:pin 0 
windowrule = match:class .* , idle_inhibit fullscreen  
windowrule = match:class Spotify, workspace 1, idle_inhibit focus
windowrule = match:class app.zen_browser.zen, workspace 2, idle_inhibit focus, scrolling_width 0.8
windowrule = match:class helium, workspace 2, idle_inhibit focus, scrolling_width 0.8
windowrule = match:class google-chrome, workspace 2, idle_inhibit focus, scrolling_width 0.8
# Hyprland dialogs like permission
windowrule = match:class hyprland-dialog, idle_inhibit always
windowrule = match:class hyprland-share-picker, float on
windowrule = match:class steam, float on, tile off, scrolling_width 0.8, workspace 10
windowrule = match:class xdg-desktop-portal-gtk, float on, tile off


# ┃  ┏━┃┃ ┃┏━┛┏━┃┏━┛
# ┃  ┏━┃━┏┛┏━┛┏┏┛━━┃
# ━━┛┛ ┛ ┛ ━━┛┛ ┛━━┛

# layerrule = blur on, match:namespace waybar
# layerrule = blur, notifications
# layerrule = ignorezero, notifications
layerrule = blur off, match:namespace logout_dialog
# layerrule = blur on, match:namespace launcher
layerrule = no_anim on, match:namespace selection
layerrule = no_anim on, match:namespace hyprpicker


# ┃┃┃┏━┃┏━┃┃ ┃┏━┛┏━┃┏━┃┏━┛┏━┛
# ┃┃┃┃ ┃┏┏┛┏┛ ━━┃┏━┛┏━┃┃  ┏━┛
# ━━┛━━┛┛ ┛┛ ┛━━┛┛  ┛ ┛━━┛━━┛

workspace = 1, layout:scrolling
workspace = 2, layout:scrolling
