# ┃ ┃┃ ┃┏━┃┏━┃┛┏━ ┃  ┏━┛
# ┏━┃━┏┛┏━┛┏┏┛┃┃ ┃┃  ┏━┛
# ┛ ┛ ┛ ┛  ┛ ┛┛━━ ━━┛━━┛

# Do not ignore/disrespect idle inhibitors of all types , as it may lead to indeterministic behaviour.
general {
  lock_cmd = pidof hyprlock || hyprlock         # Avoids starting multiple hyprlock instances
  before_sleep_cmd = loginctl lock-session      # Before going into sleep/suspend make sure systemd tells everywhere that the system is offically going into sleep mode
  # after_sleep_cmd = hyprctl dispatch dpms on  # Dont have to press multiple keys/shake mouse vigorously to come back from suspend/sleep
}

listener {
  timeout = 300                                 # Locks the user session after 5 mins
  on-timeout = loginctl lock-session            
}
listener {
  timeout = 360
  on-timeout = hyprctl dispatch dpms off        # Cuts video signal to monitor
  on-resume = hyprctl dispatch dpms on          # Wakes monitor up instantly on input
}
listener {
  timeout = 1200                                # after 20 mins put system into deep sleep
  on-timeout = systemctl suspend                
}
