# ┃ ┃┃ ┃┏━┃┏━┃━┏┛┏━┃┏━┃┃  ┃ ┃┛━┏┛
# ┏━┃━┏┛┏━┛┏┏┛ ┃ ┃ ┃┃ ┃┃  ┏┛ ┃ ┃ 
# ┛ ┛ ┛ ┛  ┛ ┛ ┛ ━━┛━━┛━━┛┛ ┛┛ ┛ 

background = 0xFF212337
# 333a47
base = 0xFF27789d
text = 0xFFe3e7fc
# accent = 0xFF73daca
accent = 0xFF97e7fd
font_family = CaskaydiaCove Nerd Font Propo
font_family_monospace = CaskaydiaCove Nerd Font Propo
font_size = 10.5
small_font_size = 8.5
h1_size = 16
h2_size = 13
h3_size = 9
icon_theme = Neuwaita
rounding_large = 0
rounding_small = 4
