# ┏┏ ┏━┃┏━ ┃ ┃┃  ┏━┛┏━┛
# ┃┃┃┃ ┃┃ ┃┃ ┃┃  ┏━┛━━┃
# ┛┛┛━━┛━━ ━━┛━━┛━━┛━━┛
source = ~/.config/hypr/hyprlangconfig/env.conf
source = ~/.config/hypr/hyprlangconfig/monitors.conf
source = ~/.config/hypr/hyprlangconfig/rules.conf
source = ~/.config/hypr/hyprlangconfig/misc.conf
source = ~/.config/hypr/hyprlangconfig/input.conf
source = ~/.config/hypr/hyprlangconfig/plugins.conf
source = ~/.config/hypr/animations/anim.conf  # 4, 7, 10, 11 and 12, 14, 15,
source = ~/.config/hypr/hyprlangconfig/keybinds.conf
source = ~/.config/hypr/hyprlangconfig/autostart.conf

# ┏━┛┏━┛┏━ ┏━┛┏━┃┏━┃┃  
# ┃ ┃┏━┛┃ ┃┏━┛┏┏┛┏━┃┃  
# ━━┛━━┛┛ ┛━━┛┛ ┛┛ ┛━━┛
general {
	border_size = 2
	gaps_in = 4
	gaps_out = 8
	col.active_border = rgba(82aaffff)
  col.inactive_border = rgba(182323ff)
	layout = dwindle
}

dwindle {
	force_split = 0
	preserve_split = true
}
scrolling {
	fullscreen_on_one_column = false
	column_width = 0.65
  follow_min_visible = 0.2
}

decoration {
	active_opacity = 1
	inactive_opacity = 0.95
	fullscreen_opacity = 1
	# rounding = 9
	# rounding_power = 5
	dim_inactive = 0
	dim_strength= 0.15

blur {
	enabled = false
	ignore_opacity = false
	size = 6
  passes = 3
  noise = 0.0117
  brightness = 0.8172
  vibrancy = 0.1696
	popups = false 
	new_optimizations = true
	xray = true  # lighter on gpu as it considers only the wallpaper for reference
}
 shadow {
	enabled = false
	range = 10
	render_power = 8
 }
}

# ┃ ┃━┃ ━┃ 
#  ┛  ┃  ┃ 
# ┛ ┛━━┛━━┛
xwayland {
  # this setting forces XWayland windows not to be scaled as Xorg cant scale properly which cause pixelated text
  force_zero_scaling = true  
}

# ┏━┃┏━┛┏━┃┏┏ ┛┏━┛┏━┛┛┏━┃┏━ ┏━┛
# ┏━┛┏━┛┏┏┛┃┃┃┃━━┃━━┃┃┃ ┃┃ ┃━━┃
# ┛  ━━┛┛ ┛┛┛┛┛━━┛━━┛┛━━┛┛ ┛━━┛
# xdg-desktop-portal implementations (including xdph) are just regular applications. They will go through permissions too.
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/bin/grim, screencopy, allow
permission = /usr/bin/slurp, screencopy, allow
permission = /usr/bin/hyprpicker, screencopy, allow
permission = /usr/bin/hyprlock, screencopy, allow
permission = .*, screencopy, ask
permission = /var/cache/hyprpm/satya/hyprland-scroll-overview/scrolloverview.so, plugin, ask
