# ┃ ┃┃ ┃┏━┃┏━┃┃  ┏━┃┏━┛┃ ┃
# ┏━┃━┏┛┏━┛┏┏┛┃  ┃ ┃┃  ┏┛ 
# ┛ ┛ ┛ ┛  ┛ ┛━━┛━━┛━━┛┛ ┛

$font = CaskaydiaCove Nerd Font Propo

general {
    hide_cursor = true
    ignore_empty_input = true
    fail_timeout = 1000
}

animations {
  enabled = true
  bezier = quart,  0.25,  1,  0.5,  1
  animation = fade,  0
  animation = inputField,  1,  10,  quart 
  animation = inputFieldFade,  0
}

background {
    monitor = 
    # path = /home/satya/Pictures/Wallpapers/Tokyonight/wallhaven-5yker3_3840x2400.png
    path = /home/satya/Pictures/Wallpapers/Tokyonight/trees.png
    # path = /home/satya/Pictures/Wallpapers/fishing_stars.jpg
    # path = /home/satya/Pictures/Wallpapers/1_1.png
    # path = /home/satya/Pictures/Wallpapers/wallhaven-lywp5y_3840x2400.png

    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# DATE – placed at the top
label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %d %Y"
    font_size = 40
    font_family = $font
    color = rgba(130, 170, 255, 1.0)
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(0, 0, 0, 0.4)
    position = 0, -180
    halign = center
    valign = top
}

# TIME – very large text below the date
label {
    monitor =
    text = <b>$TIME12</b>
    font_size = 150
    font_family = $font
    color = rgba(192, 202, 245, 1.0)
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(0, 0, 0, 0.4)
    position = 0, -260
    halign = center
    valign = top
}

label {
    monitor = 
    halign = center
    valign = center
    text =   <b>$USER</b>
    font_size = 30
    font_family = $font
    color = rgba(0, 173, 255, 1.0)
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(0, 0, 0, 0.4)
    position = -4, -320
}
# IMAGE – at the very bottom above the input field
image {
    monitor =
    path = $HOME/Pictures/icons/5.jpg
    size = 180
    rounding = 0
    border_size = 2
    border_color = rgba(130,170,255,1.0)
    position = 0, 320
    halign = center
    valign = bottom
}

# INPUT FIELD – at the very bottom
input-field {
    monitor =
    size = 480, 85
    outline_thickness = 2
    inner_color = rgba(212337ff)
    outer_color = rgba(130,170,255,1.0)
    fail_color = rgba(255, 117, 127, 1.0)
    check_color = rgba(255, 158, 100, 1.0)
    capslock_color = rgba(220, 30, 200, 1.0) 
    font_color = rgba(192, 202, 245, 1.0)
    fade_on_empty = false
    rounding = 0
    font_family = $font
    placeholder_text = 🔒 Enter your password...
    fail_text = <b>$FAIL ($ATTEMPTS)</b>
    dots_size = 0.28
    dots_spacing = 0.35
    dots_center = true
    position = 8, 160
    halign = center
    valign = bottom
}
