# ┏━┃┃  ┃ ┃┏━┛┛┏━ ┏━┛
# ┏━┛┃  ┃ ┃┃ ┃┃┃ ┃━━┃
# ┛  ━━┛━━┛━━┛┛┛ ┛━━┛

plugin {
  scrolloverview {
    scale = 0.5 # preferred overview scale
    workspace_gap = 50
    wallpaper = 2 # 0: global only, 1: per-workspace only, 2: both
    blur = true # blur only the main overview wallpaper
    shadow {
      enabled = true
      range = 40
      render_power = 4
      color = rgba(1a1a1aee)
    }
  }
  hyprbars {
    # example config
    bar_height = 22
    bar_color = rgb(212337)
    bar_text_font = "CaskaydiaCove Nerd Font"
    col.txt = rgb(c0caf5)

    # example buttons (R -> L)
    hyprbars-button = rgb(ff4040), 10, 󰖭, hyprctl dispatch killactive
    hyprbars-button = rgb(eeee11), 10, , hyprctl dispatch fullscreen 1

    # cmd to run on double click of the bar
    on_double_click = hyprctl dispatch fullscreen 1
  }
}
