--enable-features=UseOzonePlatform 
--ozone-platform-hint=wayland # hint means that if wayland not available fallback to X!!
--enable-features=WaylandWindowDecorations # disable client side decoration/tiles/borders
# --enable-zero-copy
