--enable-features=UseOzonePlatform
--ozone-platform-hint=wayland
# disable client side decoration/tiles/borders
--enable-features=WaylandWindowDecorations 
# Chromium crash workaround for Wayland color management on Hyprland - see https://github.com/hyprwm/Hyprland/issues/11957
--disable-features=WaylandWpColorManagerV1

